plugins {
    id 'com.android.application' version '8.3.2' apply true
}

android {
    namespace 'com.x.tunnel'
    compileSdk 34

    defaultConfig {
        applicationId "com.x.tunnel"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "2.0-sub"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path file("src/main/jni/Android.mk")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
}
